package model;
// default package
// Generated 2018/9/26 �U�� 02:56:56 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Certificationitem generated by hbm2java
 */
@Entity
@Table(name = "certificationitem", catalog = "mfg_world")
public class CertificationItemBean implements java.io.Serializable {

	private Integer id;
	private String area;
	private String knowledge;
	private String technical;

	public CertificationItemBean() {
	}

	public CertificationItemBean(String area, String knowledge, String technical) {
		this.area = area;
		this.knowledge = knowledge;
		this.technical = technical;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "area", length = 10)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "knowledge", length = 20)
	public String getKnowledge() {
		return this.knowledge;
	}

	public void setKnowledge(String knowledge) {
		this.knowledge = knowledge;
	}

	@Column(name = "technical", length = 20)
	public String getTechnical() {
		return this.technical;
	}

	public void setTechnical(String technical) {
		this.technical = technical;
	}

	@Override
	public String toString() {
		return "CertificationItemBean [id=" + id + ", area=" + area + ", knowledge=" + knowledge + ", technical="
				+ technical + "]";
	}

	
	
}
