// default package
// Generated 2018/8/14 �W�� 10:17:46 by Hibernate Tools 5.1.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PersonClassInfo generated by hbm2java
 */
@Entity
@Table(name = "person_class_info", catalog = "mfg_world")
public class PersonClassInfo implements java.io.Serializable {

	private int id;
	private String workNum;
	private String name;
	private String className;
	private Set<PersonClassRecord> personClassRecords = new HashSet<PersonClassRecord>(0);

	public PersonClassInfo() {
	}

	public PersonClassInfo(int id) {
		this.id = id;
	}

	public PersonClassInfo(int id, String workNum, String name, String className,
			Set<PersonClassRecord> personClassRecords) {
		this.id = id;
		this.workNum = workNum;
		this.name = name;
		this.className = className;
		this.personClassRecords = personClassRecords;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "work_num", length = 5)
	public String getWorkNum() {
		return this.workNum;
	}

	public void setWorkNum(String workNum) {
		this.workNum = workNum;
	}

	@Column(name = "name", length = 6)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "class_name", length = 20)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personClassInfo")
	public Set<PersonClassRecord> getPersonClassRecords() {
		return this.personClassRecords;
	}

	public void setPersonClassRecords(Set<PersonClassRecord> personClassRecords) {
		this.personClassRecords = personClassRecords;
	}

}
